import os
from datetime import date


DIMENSIONS = [
    "Schema & Structure",
    "Measure Completeness",
    "Naming Conventions",
    "Time Intelligence",
    "Budget & Variance",
    "Security",
    "Data Quality",
]


def score_and_report(findings: dict, config: dict) -> str:
    """
    Convert findings from the assessor into a scored Markdown report.

    Args:
        findings: Output from assessor.assess() — dict with key 'findings'.
        config: Project config dict.

    Returns:
        Absolute path to the generated report file.
    """
    report_dir = config["output"]["reports"]
    os.makedirs(report_dir, exist_ok=True)

    report_path = os.path.join(
        report_dir, f"assessment_{date.today().isoformat()}.md"
    )

    report_content = _build_report(findings["findings"])

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    print(f"Report written to: {report_path}")
    return report_path


def _build_report(findings: list[str]) -> str:
    """
    Build the Markdown report string from raw findings text.

    Args:
        findings: List of finding strings from the assessor.

    Returns:
        Full Markdown report as a string.
    """
    findings_text = "\n\n".join(findings)
    today = date.today().isoformat()

    return f"""# Assessment Report — {today}

## Executive Summary

> _Generated by BI Assessment Agent_

{findings_text}

---

## Scores by Dimension

| Dimension | Score |
|-----------|-------|
| Schema & Structure | _/10_ |
| Measure Completeness | _/10_ |
| Naming Conventions | _/10_ |
| Time Intelligence | _/10_ |
| Budget & Variance | _/10_ |
| Security | _/10_ |
| Data Quality | _/10_ |

---

_Scores to be extracted from findings in a future iteration._
"""
